version: '3.8'

services:
  react_app:
    build:
      context: ./client
    container_name: react_app
    restart: always

  node_app:
    build:
      context: ./server
    container_name: node_app
    restart: always
    expose:
      - "5000:5000"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - react_app
      - node_app
